security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\UserAuthenticator
      logout:
        path: app_logout
        # where to redirect after logout
        # target: app_any_route

      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /
        always_remember_me: true

  access_control:
    # Allow ROLE_SUPERADMIN to access any route starting with admin, superadmin, and user
    - { path: ^/admin, roles: ROLE_SUPERADMIN }
    - { path: ^/superadmin, roles: ROLE_SUPERADMIN }
    - { path: ^/user, roles: ROLE_SUPERADMIN }

    # Allow ROLE_ADMIN to access routes starting with admin and user, but not superadmin
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/user, roles: ROLE_ADMIN }

    # Restrict ROLE_USER to only access routes starting with user
    - { path: ^/user, roles: ROLE_USER }

    # Public access routes
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/reset-password, roles: PUBLIC_ACCESS }

    # Default access control for any other routes not specified above
    - { path: ^/, roles: ROLE_USER }

  role_hierarchy:
    ROLE_SUPERADMIN: [ROLE_SUPERADMIN]
    ROLE_ADMIN: [ROLE_ADMIN]
    ROLE_USER: [ROLE_USER]

when@test:
  security:
    password_hashers:
      # By default, password hashers are resource intensive and take time. This is
      # important to generate secure password hashes. In tests however, secure hashes
      # are not important, waste resources and increase test times. The following
      # reduces the work factor to the lowest possible values.
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
