home:
  path: /
  controller: App\Controller\HomeController::index

dashboard:
  path: /dashboard
  controller: App\Controller\DashboardController::index

pdf:
  resource: ../src/Controller/PdfController.php
  type: attribute

controllers_security:
  resource: ../src/Controller/SecurityController.php
  type: attribute

controllers_register:
  resource: ../src/Controller/RegistrationController.php
  type: attribute
# artbill
controllers_superadmin:
  resource: ../src/Controller/SuperAdmin
  type: attribute
  name_prefix: superadmin_
  prefix: /superadmin
# company
controllers_admin:
  resource: ../src/Controller/Admin
  type: attribute
  name_prefix: admin_
  prefix: /admin
# emplayee
controllers_user:
  resource: ../src/Controller/User
  type: attribute
  name_prefix: user_
  prefix: /user
